config/routes.rb
GoalsApp::Application.routes.draw do

  root to: 'sessions#new'

  resources :users, except: :index

  resource :session, only: [:create, :new, :destroy]

  resources :goals do
    post 'complete'
    collection { get 'admin' }
  end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :name, :completed, :private_goal, :user_id

  validates :name, :user_id, presence: true

  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :session_token, :admin
  attr_reader :password

  before_validation :ensure_session_token
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, uniqueness: true

  has_many(
    :goals,
    class_name: "Goal",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  def self.find_by_credentials(username, password)
    @user = User.find_by_username(username)

    if @user && @user.is_password?(password)
      @user
    else
      nil
    end
  end

  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(@password)
  end

  def is_password?(guess)
    BCrypt::Password.new(self.password_digest).is_password?(guess)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    return nil if session[:session_token].nil?

    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_out!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def require_log_in
    redirect_to new_session_url unless current_user
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :require_log_in
  before_filter :check_privileges, only: [:edit, :update]

  def complete
    @goal = Goal.find(params[:goal_id])
    @goal.completed = true
    @goal.save!
    redirect_to goals_url
  end

  def new
  end

  def create
    @goal = Goal.new(params[:goal])
    @goal.user_id = current_user.id

    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def index
    @my_goals = current_user.goals
    @other_peoples_goals = Goal
      .where(
        "(user_id <> :current_user_id) AND private_goal = 'f'",
        current_user_id: current_user.id
      ).includes(:user)
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update_attributes(params[:goal])
      flash.now[:messages] = ["Goal Updated!"]
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])

    @goal.destroy
    if current_user.admin?
      redirect_to user_url(@goal.user_id)
    else
      flash.now[:messages] = ["Goal Deleted!"]
      redirect_to goals_url
    end
  end

  def admin
    @users = User.all
  end

  def check_privileges
    owner_id = Goal.find(params[:id]).user_id
    redirect_to goals_url unless current_user.id == owner_id || current_user.admin?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    unless @user.nil?
      log_in!(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      log_in!(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id], include: :goals)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.admin?
      flash.now[:errors] = ["Can't delete admins!"]
      render :show
    else
      @user.destroy
      redirect_to admin_goals_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token

    "<input type=\"hidden\"
    name=\"authenticity_token\"
    value=\"#{form_authenticity_token}\">".html_safe

  end

end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/admin.html.erb
<h1 id="admin_interface">Admin Interface</h1>

<h2>Users</h2>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to "#{user.username}", user_url(user) %></li>
  <% end %>
</ul>

app/views/goals/edit.html.erb
<h1 id="set_a_new_goal">Edit Your Goal</h1>

<form action="<%= goal_url(@goal) %>" method="POST">
  <input type="hidden" name="_method" value="PUT">

  <%= auth_token %>

  <p>
    <label for="name">What are you going to accomplish?</label>
    <br>
    <input
      type="text"
      name="goal[name]"
      value="<%= @goal.name %>"
      id="name">
  </p>

  <p>
    <input
      type="hidden"
      name="goal[private_goal]"
      value="">
    <input
      type="checkbox"
      name="goal[private_goal]"
      value="true"
      id="private"
      <%= "checked" if @goal.private_goal? %>>
    <label for="private">Private</label>
  </p>

  <p>
    <input
      type="hidden"
      name="goal[completed]"
      value="">
    <input
      type="checkbox"
      name="goal[completed]"
      value="true"
      id="completed"
      <%= "checked" if @goal.completed? %>>
    <label for="completed">Completed</label>
  </p>

  <p><input type="submit" value="Update Goal"></p>
</form>

<%= button_to "Delete Goal", goal_url(@goal), method: :delete %>

<%= link_to "Cancel Update", goal_url(@goal) %>

app/views/goals/index.html.erb
<section class="page_content">

<h1 class="page_title">Look at all these goals.</h1>


<section id="my_goals_homepage">
<h2 class="section_title">My Goals</h2>

<ul id="custom-gen">
<% @my_goals.each do |goal| %>

  <li class="index_goal_name"><%= goal.name %> <%= "(Private)" if goal.private_goal? %></li>

  <ul>
      <li class="index_goal_detail"><%= link_to "Details", goal_url(goal) %></li>

      <%  unless goal.completed? %>
        <li class="index_goal_detail"><%= button_to "Complete", goal_complete_url(goal) %></li>
      <% end %>
  </ul>
  <br>
<% end %>
</ul>

<p id="set_goal_button">
  <%= link_to "Set A New Goal", new_goal_url %>
</p>

</section>

<section id="other_people_goals_homepage">
<h2 class="section_title">Other People's Goals</h2>

<ul id="custom-gen">
<% @other_peoples_goals.each do |goal| %>

  <li><%= goal.name %> (<%= goal.user.username %>)</li>
  <%= "<li>Private</li>".html_safe if goal.private_goal? %>
  <ul>
    <li class="index_goal_detail"><%= link_to "Details", goal_url(goal) %></li>
  </ul>

  <br>
<% end %>
</ul>

</section>
</section>

app/views/goals/new.html.erb
<h1 id="set_a_new_goal">Set A New Goal</h1>

<form action="<%= goals_url %>" method="POST">

  <%= auth_token %>

  <p>
    <label for="name">What are you going to accomplish?</label>
    <br>
    <input
      type="text"
      name="goal[name]"
      value=""
      id="name">
  </p>

  <p>
    <input
      type="checkbox"
      name="goal[private_goal]"
      value="true"
      id="private">
    <label for="private">Private</label>
  </p>


  <p><input type="submit" value="Set Goal"></p>
</form>

app/views/goals/show.html.erb
<!-- app/views/goals/show.html.erb -->
<section class="page_content">

<h1 class="page_title" id="look_at_this_goal.">Look at this goal.</h1>

<p>
  Goal: <%= @goal.name %>
</p>

<p>
  <%= "Private" if @goal.private_goal? %>
</p>

<p>
  <%= "Completed" if @goal.completed? %>
</p>

<p>
  <%= (link_to "Edit Goal", edit_goal_url(@goal)) if current_user == @goal.user || current_user.admin? %>
  <br>
  <%= link_to "All The Goals", goals_url %>
</p>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goals App</title>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet' type='text/css'>
</head>

<body>



<section class="site_header">
  <section class="login_info">

      <%= link_to "Admin Interface", admin_goals_url if current_user.try(:admin?) %>

    <% if current_user %>

      Currently logged in as: <%= current_user.username %>
      <%= button_to "Sign Out", session_url, method: :delete %>

    <% else %>

      <%= link_to "Sign In", new_session_url %>
      <br>
      <%= link_to "Sign Up", new_user_url %>

    <% end %>
  </section>

  <h1 class="site_title"><a href="<%= goals_url %>" id="site_title_link">MEET YOUR GOALS</a></h1>

</section>

<p>
  <%= flash[:errors] %>
</p>



<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label>
    Username:
    <input type="text" name="user[username]" value="<%= @user.try(:username) %>">
  </label>

  <br>

  <label>
    Password:
    <input type="password" name="user[password]" value="">
  </label>
  <br>

  <input type="submit" value="Sign Up">

</form>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->

<h1 >All About <%= @user.username %></h1>

<h2>Goals</h2>

<ul>
  <% @user.goals.each do |goal| %>
    <li><%= link_to "#{goal.name}", goal_url(goal) %></li>
    <ul>
    <% if current_user.admin? %>
      <li><%= link_to "Edit Goal", edit_goal_url(goal) %></li>
      <li><%= button_to "Delete Goal", goal_url(goal), method: :delete %></li>
    <% end %>
    </ul>
    <br>
  <% end %>
</ul>

<%= button_to "Delete User", user_url(@user), method: :delete %>